= Asciidoclet & Diagram for JDK 11
John Ericksen <https://github.com/johncarl81[@johncarl81]>; Ben Evans <https://github.com/benevans[@benevans]>
:description: This is a guide for setting up and using the Asciidoclet within a JDK 11 project. Asciidoclet is a Javadoc Doclet based on Asciidoctor that lets you write Javadoc in the AsciiDoc syntax.
:keywords: Asciidoclet, AsciiDoc, Asciidoctor, syntax, Javadoc, Doclet, reference
:idprefix:
:idseparator: -
:source-language: java
ifdef::env-browser[]
:sectanchors:
:source-highlighter: highlight.js
:icons: font
endif::[]
ifdef::env-github,env-browser[]
:toc: preamble
endif::[]
ifdef::env-github[]
:badges:
:!toc-title:
endif::[]
// Refs
:asciidoclet-src-ref: https://github.com/asciidoctor/asciidoclet
:asciidoclet-javadoc-ref: https://oss.sonatype.org/service/local/repositories/releases/archive/org/asciidoctor/asciidoclet/1.5.2/asciidoclet-1.5.2-javadoc.jar/!/index.html
:asciidoclet-release-ref: http://asciidoctor.org/news/2014/09/09/asciidoclet-1.5.0-released/
:asciidoc-ref: http://asciidoc.org
:asciidoctor-java-ref: http://asciidoctor.org/docs/install-and-use-asciidoctor-java-integration/
:asciidoclet-issues-ref: https://github.com/asciidoctor/asciidoclet/issues
:asciidoctor-src-ref: https://github.com/asciidoctor/asciidoctor
:asciidoctor-java-src-ref: https://github.com/asciidoctor/asciidoctor-java-integration
:discuss-ref: http://discuss.asciidoctor.org/

ifdef::badges[]
image:http://img.shields.io/travis/asciidoctor/asciidoclet/master.svg["Build Status",link="https://travis-ci.org/asciidoctor/asciidoclet"]
image:https://img.shields.io/badge/javadoc.io-1.5.4-blue.svg[Javadoc,link=http://www.javadoc.io/doc/org.asciidoctor/asciidoclet/1.5.4]
endif::[]

{asciidoclet-src-ref}[Asciidoclet] is a Javadoc Doclet based on Asciidoctor that lets you write Javadoc in the AsciiDoc syntax.

However, Java 9 completely changed the internal JavaDoc APIs in incompatible ways, making the existing Asciidoclet unusable from Java 9 onward. https://github.com/chrisvest/asciidoclet/releases/tag/2.0.0[Chris Vest] already did a lot of work to make the existing {asciidoclet-src-ref}[Asciidoclet] work and this are just some minor improvements; e.g:

* Upgraded AsciiDocterJ version to 2.3.0
* Added AsciiDoctor diagram to enable diagrams in javadoc comments.

== Example

A Java class with Asciidoclet Javadoc

----
/**
* = Asciidoclet
*
* Sample plantuml diagram
* [plantuml,test]
* ----
* class BlockProcessor
* class DiagramBlock
* class DitaaBlock
* class PlantUmlBlock
*
* BlockProcessor <|-- DiagramBlock
* DiagramBlock <|-- DitaaBlock
* DiagramBlock <|-- PlantUmlBlock
* ----
*
* Sample comments that include `source code`.
*
* [source,java]
* --
* public class Asciidoclet extends Doclet {
*     private final Asciidoctor asciidoctor = Asciidoctor.Factory.create();
*
*     @SuppressWarnings("UnusedDeclaration")
*     public static boolean start(RootDoc rootDoc) {
*         new Asciidoclet().render(rootDoc);
*         return Standard.start(rootDoc);
*     }
* }
* --
*
* @author https://github.com/johncarl81[John Ericksen]
*/
public class Asciidoclet extends Doclet {
}
----

The result is readable source and beautifully rendered Javadocs, the best of both worlds!

== Usage Maven

Asciidoclet may be used via a `maven-javadoc-plugin` doclet:

[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>3.2.0</version>
    <configuration>
         <additionalJOptions>
             <additionalJOption>-J--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED</additionalJOption> <!--1-->
             <additionalJOption>-Xdoclint:all,-html,-accessibility,-missing</additionalJOption> <!--2-->
             <additionalJOption>--base-dir</additionalJOption>
             <additionalJOption>${project.basedir}</additionalJOption>
         </additionalJOptions>
         <doclet>org.asciidoctor.asciidoclet.Asciidoclet</doclet>
         <docletArtifact>
             <groupId>org.uniknow</groupId>
             <artifactId>asciidoclet</artifactId>
             <version>2.1.0</version>
         </docletArtifact>
         <detectJavaApiLink>true</detectJavaApiLink>
    </configuration>
</plugin>
----
<1> For the asciidoclet to work, it needs access to the internals of the `javadoc` tool.
This incantation makes that access possible on moduler JDKs.
<2> Asciidoctor may generate HTML that produces doclint errors, which can cause the build to fail.
To work around that, we have to disable these doclint categories.

=== Doclet Options
// tag::doclet-options[]

--base-dir <dir>::
Sets the base directory that will be used to resolve relative path names in Asciidoc `include::` directives.
This should be set to the project's root directory.

-a, --attribute "name[=value], ..."::
Sets http://asciidoctor.org/docs/user-manual/#attributes[document attributes^] that will be expanded in Javadoc comments.
The argument is a string containing a single attribute, or multiple attributes separated by commas.
+
This option may be used more than once, for example: `-a name=foo -a version=1`.
+
Attributes use the same syntax as Asciidoctor command-line attributes:
+
--
* `name` sets the attribute (with an empty value)
* `name=value` assigns `value` to the attribute.
Occurrences of `\{name}` in the Javadoc will be replaced by this value.
* `name=value@` assigns `value` to the attribute, unless the attribute is defined in the attributes file or Javadoc.
* `name!` unsets the attribute.
--
+
The document attribute `javadoc` is set automatically by the doclet.
This can be used for conditionally selecting content when using the same Asciidoc file for Javadoc and other documentation.

-overview <file>::
Overview documentation can be generated from an Asciidoc file using the standard `-overview` option.
Files matching [x-]`*.adoc`, [x-]`*.ad`, [x-]`*.asciidoc` or [x-]`*.txt` are processed by Asciidoclet.
Other files are assumed to be HTML and will be processed by the standard doclet.

// end::doclet-options[]
// end::usage[]

== Resources and help

For more information:

* {asciidoclet-release-ref}[Asciidoclet 1.5.0 Release Notes]
* {asciidoclet-src-ref}[Asciidoclet Source Code]
* {asciidoclet-javadoc-ref}[Asciidoclet JavaDoc]
* {asciidoclet-issues-ref}[Asciidoclet Issue Tracker]
* {asciidoctor-src-ref}[Asciidoctor Source Code]
* {asciidoctor-java-src-ref}[Asciidoctor Java Integration Source Code]
* https://github.com/chrisvest/asciidoclet/releases/tag/2.0.0[Forked 2.0.0: Java 11 Support for Asciidoclet]
* https://medium.com/@chrisvest/formatting-javadoc-with-asciidoctor-and-java-11-b1912ac92bea[Formatting JavaDoc with Asciidoctor and Java 11.
]